apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:              # ✅ FIXED INDENTATION
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: gowrishankar19/project1:latest
          ports:
            - containerPort: 80
